# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3559b4ed4a9b84ebfd94a4d2e93ce1e90b36e1621748a0fc2a96236b71b73b5b3c18a3e0483c2aa9c3adf42d33e05c6f00872e693c6a38411d715ab63924361d

test:
  secret_key_base: b19c102148c920870e78a1bf83cbc825562af8c47ccefb55927714d963aba94b4fb6602e089886402b624bd40482a4a075497795763dfdc69dca5bdd15861a96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
